### ISSUE TITLE
Мутация в handleDrop

### ISSUE THREAD

**Issue by DmitriiMelnikOnix** [tatatia/React-intro#22]
Обрати внимание что ты изменяешь массив, а не создаешь новый. Когда-то из-за этого может быть побочный эффект который крайне сложно отследить, так что перед изменением массива лучше его скопировать

**Comment by DmitriiMelnikOnix** [comment]
`let array = this.state.tasks` в этой строке, так как это массив, он копируется по ссылке, то есть у тебя все еще один массив, но 2 способа обратится к нему

**Comment by DmitriiMelnikOnix** [comment]
Так же для `let array = this.state.tasks` подобных случаев отлично подходит распаковка
`const {tasks} = this.state`
или немного по другому если хочешь переименовать
`const {tasks: array} = this.state`

**Comment by tatatia** [comment]
ok, дякую, зараз буду пробувати)

**Comment by tatatia** [comment]
Виправила.
