### ISSUE TITLE
Особенности setState

### ISSUE THREAD

**Issue by DmitriiMelnikOnix** [tatatia/React-intro#25]
<img width="554" alt="Снимок экрана 2021-04-01 в 20 32 58" src="https://user-images.githubusercontent.com/59687966/113332131-7329e600-9329-11eb-8841-18ab5ad185c6.png">

setState работает достаточно интересным способом и он может объединять несколько вызовов в один, что ускоряет его работу, но из-за этого может появляться интересные побочные эффекты. В данном примере некоторые данные могу не сохранится в стейт. Так как они вызываются одновременно, и один setState перезатрет данные из другого.

Можно найти достаточно много подобных примеров, в основном они показаны в виде каких-то счетчиков

Исправить это достаточно легко, в setState нужно заменить передаваемые обьект на функцию. Примерно так
```
this.setState(({pocemons}) => ({ pocemons: [...pocemons, result] }))
```
P.S. мог запутаться в скобочках :)

**Comment by tatatia** [comment]
дякую,наче розібралась)
