### ISSUE TITLE
HOC и передача языка в пропсах

### ISSUE THREAD

**Issue by DmitriiMelnikOnix** [tatatia/React-intro#32]
Чтобы сделать красивую мультиязычность лучше в HOC создать функцию которая принимает 1 параметр - тексте, потом в зависимости от языка выбирает обьект из которого нужно достать перевод, обьект - ключ это деффолтный текст, а значение - перевод. Эту функция нужно передать из HOC в компонента в качестве пропса. А чтобы сделать переключение языков нужно использовать контекст в котором будет хранится текущий язык, в HOC будет consumer из которого нужно будет достать текущий язык и передвать в функцию описанную чуть выше

P.S. пиши в слаке если я написал что-то непонятно

**Comment by tatatia** [comment]
Доброго дня! я переробила тільки до компонента Draggable, помилку не показує, але не впевнена що правильно(
