### ISSUE TITLE
Нашел интересный баг

### ISSUE THREAD

**Issue by DmitriiMelnikOnix** [tatatia/React-intro#49]
<img width="1453" alt="Снимок экрана 2021-06-04 в 21 53 23" src="https://user-images.githubusercontent.com/59687966/120849834-4be8d280-c57f-11eb-9877-59f84e457624.png">

Если открыть страницу, потом перейти к коду `Books.js` добавить где-то перенос строки, а потом вернутся к странице то записи повторятся. Это случается из-за hot reload

**Comment by tatatia** [comment]
Исправила
